create table "public"."user_answers" (
    "id" bigint generated by default as identity not null,
    "answer" bigint not null,
    "users_id" bigint not null,
    "questions_id" bigint not null,
    "score" bigint null,
    "answered_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX user_answers_pkey ON public.user_answers USING btree (id);

alter table "public"."user_answers" add constraint "user_answers_pkey" PRIMARY KEY using index "user_answers_pkey";

alter table "public"."user_answers" add constraint "user_answers_questions_id_fkey" FOREIGN KEY (questions_id) REFERENCES questions(id) ON DELETE CASCADE not valid;

alter table "public"."user_answers" validate constraint "user_answers_questions_id_fkey";

alter table "public"."user_answers" add constraint "user_answers_users_id_fkey" FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."user_answers" validate constraint "user_answers_users_id_fkey";