create table "public"."questionnaires" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "instructions" text
);


CREATE UNIQUE INDEX questionnaires_pkey ON public.questionnaires USING btree (id);

alter table "public"."questionnaires" add constraint "questionnaires_pkey" PRIMARY KEY using index "questionnaires_pkey";