create table "public"."questions" (
    "id" bigint generated by default as identity not null,
    "text" text not null,
    "questionnaires_id" bigint not null
);


CREATE UNIQUE INDEX questions_pkey ON public.questions USING btree (id);

alter table "public"."questions" add constraint "questions_pkey" PRIMARY KEY using index "questions_pkey";

alter table "public"."questions" add constraint "questions_questionnaires_id_fkey" FOREIGN KEY (questionnaires_id) REFERENCES questionnaires(id) ON DELETE CASCADE not valid;

alter table "public"."questions" validate constraint "questions_questionnaires_id_fkey";